// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqtixompcqxzsjgjgzkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxdGl4b21wY3F4enNqZ2pnemt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMTc5MDcsImV4cCI6MjA1Nzg5MzkwN30.5bwFUr76dCaK41QHO6bbsbV-i41fMfpGEUiDdeVkEVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);